### PR TITLE
Improved UI

### PR DESCRIPTION
**Pull request by ayush7801**
Hey there, i have improved the interface of this web app. Hope you will like it and will merge it to main repo.

Screenshot (259)

### CODE REVIEW

**Comment by PoornaGTX** [comment]
Yeah its really good I can merge it. can you develop that to mobile version?. for desktop version its okay, but for mobile I want that two boxes display like vertically. you can check that by using mobile that I provided host link in repository description. Thank You for your contribution.

**Comment by ayush7801** [comment]
sure will do that

**Comment by ayush7801** [comment]
i have made this mobile responsive
127 0 0 1_5500_(Moto G4)

**Review by PoornaGTX — APPROVED** [review]
Its really very attractive and nice interface bro. I will merge this. actually I am very happy to work with you. we can do more projects. Thank you for your contribution. you can keep contribute on this project. Really appreciate your support

**Pull request merged**
